#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/the-next-coder permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# creating a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served_By $HOSTNAME:" /etc/nginx/sites-enabled/default

# test for syntax error
sudo nginx -t

# restart nginx
sudo service nginx restart
